title: "Nitin Shahi"
description: ""
theme: minima

# Remove duplicate headings
show_excerpts: false

# Navigation links (top right)
header_pages:
  - About.md
  - Research.md
  - Teaching.md

# Optional: cleaner URLs
permalink: pretty
